# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ALEX.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ALEX(object):
    def setupUi(self, ALEX):
        ALEX.setObjectName("ALEX")
        ALEX.resize(1123, 700)
        self.centralwidget = QtWidgets.QWidget(ALEX)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(-20, -20, 1281, 731))
        self.Background.setPixmap(QtGui.QPixmap("Black_Template.png"))
        self.Background.setScaledContents(True)
        self.Background.setObjectName("Background")
        self.Voice = QtWidgets.QLabel(self.centralwidget)
        self.Voice.setGeometry(QtCore.QRect(10, 520, 231, 171))
        self.Voice.setText("")
        self.Voice.setPixmap(QtGui.QPixmap("Ntuks.gif"))
        self.Voice.setScaledContents(True)
        self.Voice.setObjectName("Voice")
        self.Initial = QtWidgets.QLabel(self.centralwidget)
        self.Initial.setGeometry(QtCore.QRect(0, -50, 441, 251))
        self.Initial.setText("")
        self.Initial.setPixmap(QtGui.QPixmap("initial.gif"))
        self.Initial.setScaledContents(True)
        self.Initial.setObjectName("Initial")
        self.Dis = QtWidgets.QLabel(self.centralwidget)
        self.Dis.setGeometry(QtCore.QRect(740, 10, 391, 221))
        self.Dis.setText("")
        self.Dis.setPixmap(QtGui.QPixmap("Hero_Template.gif"))
        self.Dis.setScaledContents(True)
        self.Dis.setObjectName("Dis")
        self.Earth = QtWidgets.QLabel(self.centralwidget)
        self.Earth.setGeometry(QtCore.QRect(330, 200, 431, 251))
        self.Earth.setText("")
        self.Earth.setPixmap(QtGui.QPixmap("Earth_Template.gif"))
        self.Earth.setScaledContents(True)
        self.Earth.setObjectName("Earth")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(300, 640, 161, 71))
        self.Exit.setStyleSheet("")
        self.Exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Exit.setIcon(icon)
        self.Exit.setIconSize(QtCore.QSize(183, 150))
        self.Exit.setObjectName("Exit")
        self.Circle = QtWidgets.QLabel(self.centralwidget)
        self.Circle.setGeometry(QtCore.QRect(-10, 190, 291, 281))
        self.Circle.setText("")
        self.Circle.setPixmap(QtGui.QPixmap("giphy.gif"))
        self.Circle.setScaledContents(True)
        self.Circle.setObjectName("Circle")
        self.Ball0101 = QtWidgets.QLabel(self.centralwidget)
        self.Ball0101.setGeometry(QtCore.QRect(900, 250, 211, 131))
        self.Ball0101.setText("")
        self.Ball0101.setPixmap(QtGui.QPixmap("jhd.gif"))
        self.Ball0101.setScaledContents(True)
        self.Ball0101.setObjectName("Ball0101")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(760, 410, 361, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("kjl.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Background.raise_()
        self.Voice.raise_()
        self.Earth.raise_()
        self.Circle.raise_()
        self.Ball0101.raise_()
        self.Exit.raise_()
        self.label.raise_()
        self.Dis.raise_()
        self.Initial.raise_()
        ALEX.setCentralWidget(self.centralwidget)

        self.retranslateUi(ALEX)
        QtCore.QMetaObject.connectSlotsByName(ALEX)

    def retranslateUi(self, ALEX):
        _translate = QtCore.QCoreApplication.translate
        ALEX.setWindowTitle(_translate("ALEX", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ALEX = QtWidgets.QMainWindow()
    ui = Ui_ALEX()
    ui.setupUi(ALEX)
    ALEX.show()
    sys.exit(app.exec_())
